### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by eugene-kulak** [SectorLabs/django-postgres-extra#104]
I'm following installation instructions:
```sh
pip install django-postgres-extra
Requirement already satisfied: django-postgres-extra in /Users/keu/work/flyapps/test/.env/lib/python3.6/site-packages (1.22)
```
and I use the example from docs for partitioning:
```python
from django.db import models

from psqlextra.types import PostgresPartitioningMethod
from psqlextra.models import PostgresPartitionedModel

class MyModel(PostgresPartitionedModel):
    class PartitioningMeta:
        method = PostgresPartitioningMethod.LIST
        key = ["computation_id"]

    name = models.TextField()
    computation_id = models.Integer()


class MyModelSimple(models.Model):
    myfield = models.CharField(max_length=255)
```
after running `python manage.py pgmakemigrations` I got this:
```sh
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/keu/work/flyapps/test/mysite/catalog/models.py", line 3, in <module>
    from psqlextra.types import PostgresPartitioningMethod
ModuleNotFoundError: No module named 'psqlextra.types'
```

**Comment by rustamzh** [comment]
Pypi contains an old version 1.x. To install the new one use this command:
```
pip install git+https://github.com/SectorLabs/django-postgres-extra.git
```

**Comment by eugene-kulak** [comment]
Thanks, @rustamzh! 
Unfortunately, I'm bound to Django 1.11 :(

**Comment by kingbuzzman** [comment]
@rustamzh has something changed?

```
$ pip install git+https://github.com/SectorLabs/django-postgres-extra.git
Collecting git+https://github.com/SectorLabs/django-postgres-extra.git
  Cloning https://github.com/SectorLabs/django-postgres-extra.git to /tmp/pip-req-build-5_epod7m
  Running command git clone -q https://github.com/SectorLabs/django-postgres-extra.git /tmp/pip-req-build-5_epod7m
  Installing build dependencies ... done
....
  Stored in directory: /tmp/pip-ephem-wheel-cache-1cdesix2/wheels/29/87/40/edbda073bb85fee1f2f5bc42a3e70ebaaecfc2b26056a45215
Successfully built django-postgres-extra
$ python -c "import psqlextra"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'psqlextra'
```

it says its installed:
```
$ pip list | grep -i postgre
django-postgres-extra             2.0a15   
$ ls /usr/local/lib/python3.6/site-packages/django_postgres_extra-2.0a15.dist-info/
INSTALLER      LICENSE        METADATA       RECORD         WHEEL          top_level.txt 
$ ls /usr/local/lib/python3.6/site-packages/psqlextra
ls: cannot access '/usr/local/lib/python3.6/site-packages/psqlextra': No such file or directory
```

Any idea?

**Comment by dmcken** [comment]
Seems even that is broken:

asgiref==3.5.2
Django==4.1.2
django-filter==22.1
git+https://github.com/SectorLabs/django-postgres-extra.git@1a51b3e5457dbf7e82c5668e2d1ec4b47b32759b
django-reversion==5.0.3
django-tables2==2.4.1
gunicorn
psycopg2==2.9.4
sqlparse==0.4.3
tzdata==2022.5

In a Docker python:3.11 container I am still getting the error.
