### ISSUE TITLE
AttributeError: 'MigrationAutodetector' object has no attribute 'new_apps'

### ISSUE THREAD

**Issue by adnanrizwee** [SectorLabs/django-postgres-extra#165]
Good morning. ****I am implemented database partition plugins on my project(django-postgres-extra). Always use python manage.py pgmakemigrations for partitioned models.The model must be created by the PostgresCreatePartitionedModel operation.Do not use the standard python manage.py makemigrations command for partitioned models. Django will issue a standard CreateModel operation. Doing this will not create a partitioned table and all subsequent operations will fail. when i am try to apply pgmakemigrations then i am getting error

when apply pgmakemigrations getting error  'MigrationAutodetector'

  model = self.autodetector.new_apps.get_model(
AttributeError: 'MigrationAutodetector' object has no attribute 'new_apps'**

Please fix this issues.**

**Comment by adnanrizwee** [comment]
Traceback (most recent call last):
File "manage.py", line 22, in
execute_from_command_line(sys.argv)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/core/management/init.py", line 425, in execute_from_command_line
utility.execute()
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/core/management/init.py", line 419, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/core/management/base.py", line 373, in run_from_argv
self.execute(*args, **cmd_options)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/core/management/base.py", line 417, in execute
output = self.handle(*args, **options)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/psqlextra/management/commands/pgmakemigrations.py", line 11, in handle
return super().handle(*app_labels, **options)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/core/management/base.py", line 90, in wrapped
res = handle_func(*args, **kwargs)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 172, in handle
changes = autodetector.changes(
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/db/migrations/autodetector.py", line 43, in changes
changes = self._detect_changes(convert_apps, graph)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/db/migrations/autodetector.py", line 167, in _detect_changes
self.generate_created_models()
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/django/db/migrations/autodetector.py", line 585, in generate_created_models
self.add_operation(
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/psqlextra/backend/migrations/patched_autodetector.py", line 235, in _patched
return handler.add_create_model(operation)
File "/home/n93/Documents/Test/env/lib/python3.8/site-packages/psqlextra/backend/migrations/patched_autodetector.py", line 104, in add_create_model
model = self.autodetector.new_apps.get_model(
AttributeError: 'MigrationAutodetector' object has no attribute 'new_apps'

**Comment by adnanrizwee** [comment]
> Good morning. ****I am implemented database partition plugins on my project(django-postgres-extra). Always use python manage.py pgmakemigrations for partitioned models.The model must be created by the PostgresCreatePartitionedModel operation.Do not use the standard python manage.py makemigrations command for partitioned models. Django will issue a standard CreateModel operation. Doing this will not create a partitioned table and all subsequent operations will fail. when i am try to apply pgmakemigrations then i am getting error
> 
> when apply pgmakemigrations getting error  'MigrationAutodetector'
> 
>   model = self.autodetector.new_apps.get_model( AttributeError: 'MigrationAutodetector' object has no attribute 'new_apps'**
> 
> Please fix this issues.**

@Photonios @atul-bhouraskar @salty-horse @askoretskiy

**Comment by adnanrizwee** [comment]
def add_create_model(self, operation: CreateModel):
        """Adds the specified :see:CreateModel operation to the list of
        operations to execute in the migration."""

        model = self.autodetector.new_apps.get_model(
            self.app_label, operation.name
        )

        if issubclass(model, PostgresPartitionedModel):
            return self.add_create_partitioned_model(model, operation)
        elif issubclass(model, PostgresMaterializedViewModel):
            return self.add_create_materialized_view_model(model, operation)
        elif issubclass(model, PostgresViewModel):
            return self.add_create_view_model(model, operation)

        return self.add(operation)

**Comment by cesargalindo123** [comment]
what version django 4?

**Comment by adnanrizwee** [comment]
Yes it is fixed now after changing django version.
@cesargalindo123

**Comment by adnanrizwee** [comment]
can you tell me this packages support multiple foreign key 
@cesargalindo123  @salty-horse  @askoretskiy  @ivanp

**Comment by Photonios** [comment]
@adnanrizwee This has been fixed in version v2.0.5rc1 (just released). Django 4.0 is not supported in any older version. Please stop tagging people.
