### ISSUE TITLE
Model update crashes for invalid SQL

### ISSUE THREAD

**Issue by theikkila** [SectorLabs/django-postgres-extra#22]
Missing whitespace in https://github.com/SectorLabs/django-postgres-extra/blob/3adb6a5e43748af1941366257c3dabc2a2162704/psqlextra/compiler.py#L23

causes updates like `SomeModel.objects.all().update(flag=True)` to fail.

Problem is in compiler that generates invalid syntax.

PR #21 fixes this.

```
======================================================================
ERROR: test_something (project.tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/project/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: syntax error at or near ""id""
LINE 1: ...ATE "some_somemodel" SET "flag" = trueRETURNING "id"
                                                                   ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/project/tests.py", line 343, in setUp
    SomeModel.objects.all().update(flag=True)
  File "/code/project/ENV/src/django-postgres-extra/psqlextra/manager.py", line 104, in update
    rows = compiler.execute_sql(CURSOR)
  File "/code/project/ENV/src/django-postgres-extra/psqlextra/compiler.py", line 14, in execute_sql
    cursor.execute(sql, params)
  File "/code/project/ENV/lib/python3.6/site-packages/raven/contrib/django/client.py", line 114, in execute
    return real_execute(self, sql, params)
  File "/code/project/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self.cursor.execute(sql, params)
  File "/code/project/ENV/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/code/project/ENV/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/code/project/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: syntax error at or near ""id""
LINE 1: ...ATE "some_somemodel" SET "flag" = trueRETURNING "id"
                                                                   ^

```

**Comment by Photonios** [comment]
Fixed in #21.
