### ISSUE TITLE
.values() and .values_list() unsupported in GenericRelation

### ISSUE THREAD

**Issue by Nekmo** [SectorLabs/django-postgres-extra#77]
`.values()` and `.values_list()` does not work in GenericRelation when django Postgres Extra is used. An error occurs when the methods are used. Without django-postgres-extra it works as it should. 

**Environment**:
Tested in Django 2.1 and Django 2.2. Python 3.7.

**Model**:
```
class Ip(BigAutoFieldBase, DetectionBase, WhoisBase, Model):
    inet = CidrAddressField(_('INET'), unique=True, db_index=True)

    detections = GenericRelation(Detection, object_id_field='object_id',
                                 related_query_name='ip')
    objects = IpManager()
```

**Query**:
```
        return list(set(obj['best_result'].detections.values_list('type', flat=True)))
```

**Traceback:**
```
Traceback (most recent call last):
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nekmo/Workspace/xxxxxx/inet/api/viewsets.py", line 20, in create
    self.perform_create(serializer)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/nekmo/Workspace/xxxxxx/inet/api/serializers.py", line 135, in create
    ), context=context).data
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/serializers.py", line 563, in data
    ret = super(Serializer, self).data
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/rest_framework/fields.py", line 1889, in to_representation
    return method(value)
  File "/home/nekmo/Workspace/xxxxxx/inet/api/serializers.py", line 111, in get_detection_types
    return list(set(obj['best_result'].detections.values_list('type', flat=True)))
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/db/models/query.py", line 774, in values_list
    clone = self._values(*_fields, **expressions)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/db/models/query.py", line 742, in _values
    clone.query.set_values(fields)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1984, in set_values
    self.add_fields(field_names, True)
  File "/home/nekmo/.virtualenvs/xxxxxx/lib/python3.7/site-packages/psqlextra/query.py", line 116, in add_fields
    _, targets, _, joins, path = self.setup_joins(parts, opts, alias, allow_many=allow_m2m)
ValueError: too many values to unpack (expected 5)
[09/May/2019 10:35:43] "POST /api/search/ HTTP/1.1" 500 156723
```

![Screenshot_20190509_104154](https://user-images.githubusercontent.com/740106/57439886-3e00e000-7247-11e9-9d3a-5e9f077ea4bf.png)

**Comment by Photonios** [comment]
Please try with version `1.21a16` from PyPi:

```
pip install django-postgres-extra==1.21a16
```

This alpha release has a fix in it and is fully compatibile with Django 2.2.

**Comment by Nekmo** [comment]
Thanks, I'll try tomorrow at work :)
